# -*- coding: utf-8 -*-
"""Homework Day 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIKOcchcDFMZw6nP_ZlW9rwKJGkME9yN
"""

#Question 1
myList = list(range(10))
print(myList)

middle_index = len(myList)//2

first_half = myList[:middle_index]

second_half = myList[middle_index:]

swappedList = second_half + first_half

print(swappedList)

#Question 2

n = int(input("Please enter a single digit even integer: "))

mylist = list(range(0,n+1,2))

if 0<= n < 10 and n%2 == 0:  
 print(mylist)

else:
  print("Not a valid number")