# -*- coding: utf-8 -*-
"""Homework Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3z0-Ow8Cf5A1E69zp7E7Tlw1V3EgAmP
"""

#Question 1 - User Login Application

print("User Login Application")

user_name = "Beste"
password ="password"

user_name1 =input("Please enter your user name: ")

password1= input("Please enter your password: ")

if (user_name != user_name1 and password == password1):
    print("Invalid user name")
elif (user_name==user_name1 and password != password1):
    print("Invalid Password")
elif (user_name != user_name1 and password!= password1):
    print("Invalid user name and password")
else:
    print("You are now logged in!")

#Question 2 - Extra

print("User Login Application")

user = {'Beste': 'password'}

user_name2 = input("Please enter your user name: ")

password2= input("Please enter your password: ")

if user_name2 not in user and password2 in user.values():
    print("Invalid user name")
elif user_name2 in user and password2 not in user.values():
    print("Invalid Password")
elif user_name2 not in user and password2 not in user.values():
    print("Invalid user name and password")
else: 
    print("You are now logged in!")