# -*- coding: utf-8 -*-
"""Homework Day 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HwJZxvRNe1C5pnntwzpBUojHed6WnLxR
"""

class Animals():
  def __init__(self, species, name, sound):
    self.species = species
    self.name = name
    self.sound = sound

  def print_name(self):
      print(self.species + " is named " + self.name)

dog1 = Animals("Dog", "Puppy", "woof")
dog1.print_name()

class Dogs(Animals):
  def __init__(self, species, name, sound, fav_activity, legs):
      super().__init__(species, name, sound)  
      self.fav_activity = fav_activity
      self.legs = legs

  def print_sentence(self):
      print(self.name + " is a " + self.species + " who loves to " + self.fav_activity + " by making the sound " + self.sound + " and has " + str(self.legs) + " legs." )

my_dog = Dogs("Dog", "Boncuk", "woof", "bark", 4)

my_dog.print_sentence()

class Cats(Animals):
  def __init__(self, species, name, sound, char, tail):
      super().__init__(species, name, sound)
      self.char = char
      self.tail = tail
  
  def print_activity(self):
      print("My " + self.species + " " + self.name + " has a " + self.tail + " tail and she is the most " + self.char + " cat ever. She barely " + self.sound + "s." )


my_cat = Cats("cat", "Leyla", "meow", "calm", "long")

my_cat.print_activity()