# -*- coding: utf-8 -*-
"""Homework Day 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfKXE5hODgsAAWrbi7n_8is21JSRgaJF
"""

prime_numbers = 0

def prime_number(x):
    if x >= 2:
      for y in range(2,x):
        if not ( x % y ):
          return False
    else:
	    return False
    return True
	        

for i in range(101):
    if prime_number(i):
      prime_numbers += 1
      print(i)